apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: video-processor-auth
  labels:
    app: auth-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3002'
    prometheus.io/path: '/metrics'
spec:
  type: LoadBalancer
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: auth-service