apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres
  namespace: video-processor-auth
  labels:
    app: auth-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "auth_db"
        - name: POSTGRES_USER
          value: "auth_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-service-secret
              key: POSTGRES_PASSWORD
        # Volume mount removed for no-storage deployment
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - auth_user
            - -d
            - auth_db
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - auth_user
            - -d
            - auth_db
          initialDelaySeconds: 5
          periodSeconds: 5
      # Volumes removed for no-storage deployment