apiVersion: v1
kind: Service
metadata:
  name: auth-redis
  namespace: video-processor-auth
  labels:
    app: auth-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: auth-redis